CachingTutorial/Controllers/CachingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CachingTutorial.Controllers
{
    public class CachingController : Controller
    {
        // GET: Caching : Cambiar Modo de Visualización

        //[OutputCache(Duration = 20, VaryByParam ="mode")]
        //[OutputCache(CacheProfile = "NoParam20Secs")]
        public ActionResult ChangeMode(bool? mode, int? dark, int? clear)
        {

            if (mode != null)
            {
                bool? ScreenMode = mode;

                if (ScreenMode == true)
                {
                    ViewBag.Mode = true;

                    dark++;
                    ViewBag.DarkCalls = dark;
                    ViewBag.ClearCalls = clear;
                }
                else if (ScreenMode == false)
                {
                    ViewBag.Mode = false;

                    clear++;
                    ViewBag.ClearCalls = clear;
                    ViewBag.DarkCalls = dark;
                }

            }
            else if (mode == null)
            {

                ViewBag.Mode = false;
                ViewBag.DarkCalls = 0;
                ViewBag.ClearCalls = 0;

            }
            ViewBag.Fecha = DateTime.Now.ToLongDateString().ToUpper();
            ViewBag.Hora = DateTime.Now.ToLongTimeString();
            return View();
        }
    }
}

CachingTutorial/Views/Caching/ChangeMode.cshtml
@{
    ViewBag.Title = "ChangeMode";
}

@{
    bool mode = ViewBag.Mode;
    int dark = ViewBag.DarkCalls;
    int? clear = ViewBag.ClearCalls;

    if (mode == true)
    {

        Layout = "~/Views/Shared/_LayoutCustomDark.cshtml";
        
        ViewBag.DarkCalls = dark;
        ViewBag.ClearCalls = clear;

    }
    else if (mode == false)
    {

        Layout = "~/Views/Shared/_LayoutCustomClear.cshtml";
       
        ViewBag.ClearCalls = clear;

    }

}

<h4><b>Cambio de Modo: Oscuro/Claro</b></h4>
<hr />
<div class="mode">
    <h4>Llamadas al modo oscuro: @ViewBag.DarkCalls</h4>
    <h4>Llamadas al modo claro: @ViewBag.ClearCalls</h4>
    <br /><h2><span class="badge badge-dark">Hora del Sistema: @ViewBag.Hora</span></h2>
</div>
<br />

<span class="badge badge-warning">Durante 20 segundos el Caching estará activo: No podrá cambiar el modo</span>

<div class="progress">
    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
        <span id="current-progress">Tiempo de Caching restante</span>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
    </div>
    <div style="height:100px" class="col-md-4">
        <div><span id="time" class="badge badge-dark"></span></div>
    </div>
    <div class="col-md-4">
    </div>
</div>


<div class="row">

    <div class="col-md-6">
        <div class="text-center">
            <div class="mode">

                @Html.ActionLink("Modo Oscuro", "ChangeMode", "Caching", new { mode = true, dark = ViewBag.DarkCalls, clear = ViewBag.ClearCalls }, new { @class = "btn btn-dark btn-md", @id = "ModoOscuro"})
                <div id="hide">

                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="text-center">
            <div class="mode">
                @Html.ActionLink("Modo Claro", "ChangeMode", "Caching", new { mode = false, clear = ViewBag.ClearCalls, dark = ViewBag.DarkCalls }, new { @class = "btn btn-primary btn-md", @id = "ModoClaro" })
                <div id="hide2">

                </div>
            </div>
        </div>
    </div>
</div>

CachingTutorial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CachingTutorial/Views/Shared/_LayoutCustomClear.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>


    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/generalClear.css" rel="stylesheet" />
    <style>
        .progress {
            margin: 0px;
            width: 100%;
            height: 20px;
        }

        #current-progress {
            padding-bottom: 0px;
        }
    </style>
</head>
<body>
    <div id="contenedor">
        <div class="menu">
            <ul class="sticky">

                <li id="logoMain" class="active"></li>
                <li class="activeTheme"><span class="titleBigTheme">Tutorial</span></li>
                <li class="active"><span class="titleBig">Caching en MVC</span></li>

            </ul>

        </div>

        <article>
            <div class="ContentShop">
                <div class="content">
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->

                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-8">
                            <div class="text-center">

                                <div style="height:60px"></div>


                                @RenderBody()

                            </div>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->
                </div>

            </div>
        </article>
        <footer>
            <div>
                <span class="footer">

                    Petruse Uwaleke Mejías
                    <a class="foot" href="mailto:petrus.uwaleke@tajamar365.com">petrus.uwaleke@tajamar365.com</a>
                </span>
            </div>
        </footer>
    </div>


    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <script type="text/javascript">

        var i = 100;

        var counterBack = setInterval(function () {

            i -= 5;

            if (i >= 0) {

                $("#time").text((i / 5).toString() + " secs");
                $('.progress-bar').css('width', i + '%');

            } else {
                clearInterval(counterBack);
            }

        }, 1000);

    </script>

</body>

</html>

CachingTutorial/Views/Shared/_LayoutCustomDark.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>


    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/generalDark.css" rel="stylesheet" />
    <style>
        .progress {
            margin: 0px;
            width: 100%;
            height: 20px;
        }

        #current-progress {
            padding-bottom: 0px;
        }
    </style>
</head>
<body>
    <div id="contenedor">
        <div class="menu">
            <ul class="sticky">

                <li id="logoMain" class="active"></li>
                <li class="activeTheme"><span class="titleBigTheme">Tutorial</span></li>
                <li class="active"><span class="titleBig">Caching en MVC</span></li>

            </ul>

        </div>

        <article>
            <div class="ContentShop">
                <div class="content">
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->

                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-8">
                            <div class="text-center">

                                <div style="height:60px"><h3><span class="badge bg-success">Modo Oscuro Activado</span></h3></div>


                                @RenderBody()

                            </div>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->
                    <!--CONTENT///////////////////////////////////////////////////////////////////////////////////////////////-->
                </div>

            </div>
        </article>
        <footer>
            <div>
                <span class="footer">

                    Petruse Uwaleke Mejías
                    <a class="foot" href="mailto:petrus.uwaleke@tajamar365.com">petrus.uwaleke@tajamar365.com</a>
                </span>
            </div>
        </footer>
    </div>


    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <script type="text/javascript">

        var i = 100;
        var counterBack = setInterval(function () {

            i -= 5;

            if (i >= 0) {

                $("#time").text((i / 5).toString() + " secs");
                $('.progress-bar').css('width', i + '%');

            } else {
                clearInterval(counterBack);
            }

        }, 1000);

    </script>

</body>

</html>